### ISSUE TITLE
home-manager as a nix-darwin module?

### ISSUE THREAD

**Issue by pwnwriter** [lanjoni/snowflake#1]
hey, I see you are manually running nix-darwin from result, I just wanted to ask, is it possible to directly install nix-darwin to $PATH and run home-manager as a module?  or did I miss something? 

Thanks for the response !!

**Comment by lanjoni** [comment]
Hey! Hope everything is ok! 

Well, you can install nix-darwin to $PATH using these commands:
```
nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
./result/bin/darwin-installer
```
> Refer to https://github.com/LnL7/nix-darwin?tab=readme-ov-file#installing

But, installing nix-darwin to $PATH into your Mac maybe will be a problem if in the future you want to remove it. The simple tutorial which I used to build this entire configuration is available on [YouTube](https://youtu.be/LE5JR4JcvMg?si=ahAwaokC5bfcE9Jz).

Hope this can help you! If you have any questions, please feel free to ask! Thanks!

**Comment by pwnwriter** [comment]
Correct me if I'm wrong; as I'm also new to this,   nix-darwin mentions that if we are using flakes, [we don't need to use Darwin-installer](https://github.com/LnL7/nix-darwin?tab=readme-ov-file#flakes).

What's up with that?

**Comment by lanjoni** [comment]
Yes, exactly! If you're using flakes, it will control your inputs and outputs in general. Nix Darwin don't work exactly as NixOS rebuild system, so if you are using flakes you don't need to install it, flakes will manage the module for you.

**Comment by pwnwriter** [comment]
I added nix-darwin on my config. If you have any feedback please provide. 

https://github.com/pwnwriter/nix
